super_admin:
  - Renalware::Role
admin:
  - Renalware::User
  - Renalware::BagType
  - Renalware::Drugs::Drug
  - Renalware::Drugs::Type
  - Renalware::EdtaCode
  - Renalware::Events::Type
  - Renalware::MedicationRoute
  - Renalware::Modality::Description
  - Renalware::OrganismCode
  - Renalware::PRDDescription
