super_admin:
  - Renalware::Role
  - Renalware::Hospitals::Ward
  - Renalware::Hospitals::Centre
  - Renalware::Hospitals::Unit
  - Renalware::HD::Dialysate
  - Renalware::HD::Dialyser
  - Renalware::HD::CannulationType
  - Renalware::System::Download
  - Renalware::Pathology::ObservationDescription
admin:
  - Renalware::User
  - Renalware::BagType
  - Renalware::Drugs::Drug
  - Renalware::Drugs::Type
  - Renalware::EdtaCode
  - Renalware::Events::Type
  - Renalware::MedicationRoute
  - Renalware::Modality::Description
  - Renalware::OrganismCode
  - Renalware::PRDDescription
  - Renalware::HD::TransmissionLog
  - Renalware::HD::Station
